name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_notes:
        description: 'Release notes'
        required: false
        default: 'New release'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      shell: pwsh

    - name: Build regular release
      run: dotnet build -c Release --no-restore
      shell: pwsh

    - name: Publish single-file release
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish
      shell: pwsh

    - name: Create release package
      run: |
        Compress-Archive -Path ".\publish\NetKit.exe" -DestinationPath "NetKit-$env:VERSION.zip"
      shell: pwsh
      env:
        VERSION: ${{ github.event.inputs.version }}

    - name: Create GitHub Release
      run: |
        $version = $env:VERSION
        $title = "NetKit $version"
        $notes = $env:RELEASE_NOTES
        $notes | Out-File -FilePath "release_notes.txt" -Encoding UTF8 -NoNewline
        gh release create $version "NetKit-$version.zip" --title $title --notes-file "release_notes.txt"
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.event.inputs.version }}
        RELEASE_NOTES: ${{ github.event.inputs.release_notes }}