name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_notes:
        description: 'Release notes'
        required: false
        default: 'New release'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build regular release
      run: dotnet build -c Release --no-restore

    - name: Publish single-file release
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish

    - name: Create release package
      run: |
        # Create single-file release package with just the exe
        Compress-Archive -Path "./publish/NetKit.exe" -DestinationPath "NetKit-${{ github.event.inputs.version }}.zip"
      shell: powershell

    - name: Create GitHub Release
      run: |
        gh release create "${{ github.event.inputs.version }}" "./NetKit-${{ github.event.inputs.version }}.zip" --title "NetKit ${{ github.event.inputs.version }}" --notes "${{ github.event.inputs.release_notes }}"
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}